### ISSUE TITLE
[Spatial Partition] Error when run App.java

### ISSUE THREAD

**Issue by tiennm99** [iluwatar/java-design-patterns#2544]
When run [App.java](https://github.com/iluwatar/java-design-patterns/blob/5b147b00367a500e8dfeac882d4b0d6a0540c6b9/spatial-partition/src/main/java/com/iluwatar/spatialpartition/App.java), there are some problems:
- `ConcurrentModificationException` happen:
```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
	at com.iluwatar.spatialpartition.Bubble.handleCollision(Bubble.java:69)
	at com.iluwatar.spatialpartition.App.lambda$noSpatialPartition$0(App.java:75)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.iluwatar.spatialpartition.App.noSpatialPartition(App.java:70)
	at com.iluwatar.spatialpartition.App.main(App.java:125)
```
- Some logs don't work, just log `"Bubble"`
- Some logs don't use Slf4j formatting anchor _{}_.

**Comment by tiennm99** [comment]
I'm working on it

**Comment by rawat1101** [comment]
1: at line no 66(var bubblesToCheck = bubbles.values();) and at ln :70      you are iterating it (bubbles.forEach) and inside handleCollision() method you are updating the same map(bubbles,inside pop() allBubbles.remove(this.id);) . 
Thats why once you get the iterator from a collection you can not modify the collection(if map changes the babbles.values() also affected).
2:same for withSpatialPartition() method LN:93 bubbles.forEach
3: same for noSpatialPartition() method LN 70:bubbles.forEach
