### ISSUE TITLE
Build failing due to problem in urm-maven-plugin

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#492]
The last Travis build has failed due to following error:

[ERROR] Failed to execute goal com.github.markusmo3.urm:urm-maven-plugin:1.4.0:map (default) on project promise: Execution default of goal com.github.markusmo3.urm:urm-maven-plugin:1.4.0:map failed: 3 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.markusmo3.urm:urm-maven-plugin:1.4.0:map (default) on project promise: Execution default of goal com.github.markusmo3.urm:urm-maven-plugin:1.4.0:map failed: 3
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.markusmo3.urm:urm-maven-plugin:1.4.0:map failed: 3
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at de.markusmo3.urm.domain.DomainExecutable.getUmlName(DomainExecutable.java:39)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.lambda$describeDomainClassConstructors$2(PlantUMLPresenter.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.describeDomainClassConstructors(PlantUMLPresenter.java:101)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.describeDomainClass(PlantUMLPresenter.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.listDomainClasses(PlantUMLPresenter.java:63)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.describePackage(PlantUMLPresenter.java:56)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.describePackages(PlantUMLPresenter.java:50)
	at de.markusmo3.urm.presenters.PlantUMLPresenter.describe(PlantUMLPresenter.java:157)
	at de.markusmo3.urm.DomainMapper.describeDomain(DomainMapper.java:37)
	at de.markusmo3.urm.DomainMapperMojo.execute(DomainMapperMojo.java:70)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

**Comment by markusmo3** [comment]
* https://github.com/markusmo3/uml-reverse-mapper/commit/be4e2d784af53dd9da06d0e999eab715740a9950
* https://github.com/markusmo3/uml-reverse-mapper/commit/d70849526c4de1ace66668accfd44dba3637456a

Fixed in Version 1.4.1, tested locally, already deployed, waiting for central maven to update

**Comment by markusmo3** [comment]
This issue still persists, i will work on it another day though

**Comment by iluwatar** [comment]
@markusmo3 is it this issue https://github.com/markusmo3/uml-reverse-mapper/issues/1 ?

**Comment by markusmo3** [comment]
no, thats another problem for another time, but because it doesnt block funtionality it is very low priority.

With the newest commit https://github.com/iluwatar/java-design-patterns/commit/fa52a7f77eb038cf7e67bf9dfa32089b1fec096b the problem seems to be gone again
